### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ScopeyNZ** [ScopeyNZ/Debug#1]
- [ ] Organise ~~loggables~~ everything a bit better
- [ ] Extract and make adapters for the file writing stuff
  - Decide whether to use something like monolog although PSR3 seems like overkill
- [ ] Write a component (maybe as a separate repo) to display a log file
- [ ] Implement a sanitizer for the SQL parameters - even though this should only be used in development
